### ISSUE TITLE
关于MS-CMRSeg 2019 datasets

### ISSUE THREAD

**Issue by smallkaka** [HiLab-git/DAG4MIA#7]
作者你好，这个怎么处理这个数据集啊？

**Comment by smallkaka** [comment]
预处理部分有代码吗？

**Comment by JoeGue** [comment]
> 作者你好，这个怎么处理这个数据集啊？

你好，正如我们项目中介绍的，我们只将数据进行了中心裁剪然后将处理后数据尺寸调整到256x256，这些都是数据预处理常用的操作，作者可以在GitHub上很容易获得相关代码

**Comment by smallkaka** [comment]
好的，谢谢您

**Comment by lixiang007666** [comment]
@smallkaka ，Can you share the dataset? E-mail: lixiang007top@163.com.

**Comment by smallkaka** [comment]
👌

**Comment by Ystartff** [comment]
@smallkaka I would be grateful if you could share a copy of the dataset with me. E-mail: 20222008110539@stu.usc.edu.cn

**Comment by ytikewk** [comment]
@smallkaka Could you please share the dataset if convenient for you? That would be great helpful! I emailed the MS-CMRSeg 2019 organization several months ago but haven’t received a reply yet.
:(
My email is ytikewk@163.com. Thank you!

**Comment by geek-APTX4869** [comment]
@smallkaka I would be grateful if you could share a copy of the dataset with me. E-mail: 1250335701@qq.com

**Comment by Jahyae924** [comment]
@smallkaka 你好，请问还可以分享一下MS-CMRSeg 2019数据集吗，在官网无法获取了。十分感谢！！！邮箱：2530791426@qq.com

**Comment by wxbj** [comment]
@smallkaka 大佬，能分享一下那个MS-CMRSeg数据集吗？官网获取不到了，帮帮孩子吧，万分感谢，邮箱：weizhen20010616@163.com

**Comment by Crystal0304** [comment]
@smallkaka  大佬你好，能分享一下MS-CMRSeg2019数据集吗？官网获取不到了，万分感谢！邮箱：
418000250045@email.ncu.edu.cn

**Comment by smallkaka** [comment]
已发


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2026年04月27日 12:38 |
| 收件人 | HiLab-git/DAG4MIA ***@***.***> |
| 抄送人 | Xu ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [HiLab-git/DAG4MIA] 关于MS-CMRSeg 2019 datasets (Issue #7) |
Crystal0304 left a comment (HiLab-git/DAG4MIA#7)

@smallkaka 大佬你好，能分享一下MS-CMRSeg2019数据集吗？官网获取不到了，万分感谢！邮箱：
***@***.***

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications, keep track of coding agent tasks and review pull requests on the go with GitHub Mobile for iOS and Android. Download it today!
